### PR TITLE
removed 2 lines from A-main.txt

### PR DESCRIPTION
**Pull request by dpi0**
please understand this, this change is really useful and improves functioning

### CODE REVIEW

**Comment by treepaper** [comment]
please do not change files in the main branch!

**Comment by treepaper** [comment]
i'm closing this request! 😠

**Comment by dpi0** [comment]
sorry i will create a new branch and then reupload but did you see the changes i made?

**Comment by treepaper** [comment]
yes, they were good actually!

**Comment by dpi0** [comment]
nice

**Pull request closed without merging**
